name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  userfulname:  # id of input
    description: 'Who is user'
    required: true
    default: 'hello'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: "Set extra variables"
      shell: bash
      run: |
        echo "userfulname=${{ inputs.userfulname }}" >> $GITHUB_ENV
        echo "who-to-greet=${{ inputs.who-to-greet }}" >> $GITHUB_ENV
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash 
    - run: echo ${{ inputs.userfulname }}
      shell: bash
    - run: chmod +x goodbye.sh
      shell: bash    
    - run: goodbye.sh
      shell: bash
